### ISSUE TITLE
Χρήστης(πεδία, μέθοδοι, επικοινωνία με server)

### ISSUE THREAD

**Issue by konsgavriil** [filcar/ClosestOfferFinder#10]
Δημιουργία κλάσης user η οποία θα έχει fields(τοποθεσία,x,y,username,password).
Δημιουργία μεθόδων όπως enterCoordinates.
Και υλοποίηση επικοινωνίας μεταξύ κλάσεων.

**Comment by dev23cc** [comment]
Βασικα σκεφτόμουνα ενα Interface User(userDetails,location) Το userDetails και location θα είναι σύνθετοι τύποι δεδομένων. Το user, θα έχει κάποιο μοναδικο id πάντα το οποιο θα δημιουργείται οταν πρωτοανοιγει η εφαρμογή, και αλλα προεραιτικά πεδια που θα βαλουμε αργότερα. Το location θα εχει 2 πεδια γεωγραφικό μήκος γεωγραφικό πλάτος

**Comment by konsgavriil** [comment]
To location καλύτερα να έχει και ένα τρίτο πεδίο πόλη για να γίνεται καλύτερη διευκρίνηση για το που βρίσκεται ο χρήστης. Σκέψου ότι με το να αλλάζεις πόλη θα αλλάζεις κατα κάποιο τρόπο χάρτη...Αλλά θα δούμε πως θα το υλοποιήσουμε όταν μαζευτούμε όλα τα μέλη..

**Comment by filcar** [comment]
Αν η πρόσβαση του χρήστη γίνεται με user και pass τότε αυτό θα σημαίνει περισορισμό στην πρόσβαση. Το θέλουμε όμως αυτό. Το θέλουμε σίγουρα στην περίπτωση των προμηθευτών - καταστηματων που θα μπαίνουν στην εφαρμογή για να καταχωρούν τις προσφορές τους. Μάλλον όχι όμως για τους απλούς χρήστες που μάλλον θα πρέπει να είναι και ανώνυμοι (παραβίαση προσωπίκών δεδομένων αν καταχωρούνται οι συνήθειες τους. Η απόδοση όμως ενός μοναδικού id στον χρήστη κατά την εγκατάσταση της εφαρμογής είναι επιθυμητή αφού με εξόρυξη δεδομένων μπορών να ληφθούν συμπεράσματα.

**Comment by dev23cc** [comment]
@gavrilinos την πόλη και τη χώρα θα μπορουμε να την παίρνουμε μέσω των συντεταγμένων, ρωτώντας api της google

@filcar Όλοι οι χρήστες του συστήματος θα παίρνουν μοναδικο id ακομα και οι προμηθευτές. Αρχικά για όλους(χρήστες, επιχειρήσεις) θα έχουμε μόνο μέσω του id συνδεση. Στη συνεχεια θα υλοποιήσουμε είσοδο μεσω κωδικου για επιχειρήσεις και στο τελος αν προλαβουμε και για τους χρήστες. Όσον αφορά για τους χρήστες μπορούμε να έχουμε μια άδεια χρήσης και πολιτική απορρήτου, με την οποία θα πρέπει να συμφωνούν. Έτσι θα μπορούμε να έχουμε τη ρητή συναίνεσή, στην κάθε είδους επεξεργασία των προσωπικών τους δεδομένων, και σε κάθε μορφή εξόρυξης και εκμετάλευσης αυτών. Αυτές οι δυνατότητες θα μπούν και θα υλοποιηθούν σιγά - σιγά μεσα στο userDetails
