### ISSUE TITLE
Server(πεδία, μέθοδοι, επικοινωνία με users και StubDao)

### ISSUE THREAD

**Issue by konsgavriil** [filcar/ClosestOfferFinder#12]
Ο server θα παίζει κατα κάποιο τρόπο τον ρόλο του διαμεσολαβητή μεταξύ user και των εγγραφών στο StubDao. Δηλαδή θα υπάρχει μια αμφίδρομη επικοινωνία και από τις δύο μεριές του server, με τελικό σκοπό την λήψη των προσφορών από τον user. Βάση αυτών των προδιαγραφών πρέπει να τεκμηριωθεί η δήλωση του server.

**Comment by dev23cc** [comment]
θα υπάρχει πρόβλεψη για μελλοντικες περισσότερες πληροφορίες (εγγραφή χρήστη, αγαπημένες κατηγορίες χρήστη, κλπ)
