### ISSUE TITLE
StubDao(Από αυτό θα λαμβάνει στοιχεία ο server αντί για μια βάση δεδομένων)

### ISSUE THREAD

**Issue by konsgavriil** [filcar/ClosestOfferFinder#14]
Αυτή θα είναι μια πρώτη υλοποίηση, η οποία θα μας βοηθήσει να δούμε αν με την σχεδίαση που κάναμε στον server θα μπορεί να αντληθεί από οποιαδήποτε πηγή ένα σύνολο πληροφοριών.

**Comment by dev23cc** [comment]
Βασικά στον Server θα έχουμε interface IDao, και θα φτιαξουμε μια υλοποίηση StubDao που θα κάνει implement το ΙDao, ώστε μετα να μπορουμε να κάνουμε ένα MySQLDao
