### ISSUE TITLE
Προσθήκη Φίλτρου

### ISSUE THREAD

**Issue by konsgavriil** [filcar/ClosestOfferFinder#2]
Αυτό το issue αφορά την προσθήκη φίλτρου το οποίο θα ελέγχει τον τύπο της προσφοράς(ρούχα,φαγητό κτλπ). Αλλιώς αν δεν υπάρχει κάποια επιλογή από τον χρήστη η εφαρμογή θα προβάλει όλα τα είδη προσφορών κοντά στον χρήστη.

**Comment by dev23cc** [comment]
its best I think to create an interface for that (IOffer like), that would include categories

**Comment by konsgavriil** [comment]
Δεν μιλάω για το πως θα γίνει η υλοποίηση της προσφοράς..πρώτα τεκμηριώνουμε ιδέες.

**Comment by dev23cc** [comment]
τεκμηριώσεις καλυτερα να γινονται milestones γιατι ειναι user stories

**Comment by filcar** [comment]
Καλύτερα να περιγράψουμε αναλυτικότερα τις απαιτήσεις του χρήστη σε φίλτρα.

**Comment by dev23cc** [comment]
Κάποιοio interface Category

**Comment by JohnPapadopoulos** [comment]
Σε συνέχεια του αρχικού, προτείνω και τα εξής:

α) Εμφάνιση τελευταίων προσφορών
β) >> προσφορών που λήγουν (πχ μένουν 12 ώρες)
γ) >> των προσφορών με τις περισσότερες θεάσεις.

**Comment by dev23cc** [comment]
Νομιζω οτι το α και β μπορούν να υλοποιηθούν χωρις την υπαρξη του serrver στην εφαρμογή του Client. Για το γ κάθε φορά που βλέπει ενα id μια προσφορά η εφαρμογή του client θα πρέπει να στελνει το γεγονός στον Server
