### ISSUE TITLE
Ένδειξη απόστασης 

### ISSUE THREAD

**Issue by konsgavriil** [filcar/ClosestOfferFinder#3]
Θα ήταν ωραίο για τον χρήστη να λαμβάνει την απόστασή του από την προσφορά που επιλέγει. Αυτό το issue δεν θεωρείται πρωτεύουσας σημασίας αλλά θα μπορούσε να βελτιώσει την εμφάνιση της εφαρμογής σε μεγάλο βαθμό.

**Comment by dev23cc** [comment]
Getting his distance based on an offer is really an improvment that should be in the third category (in importance). Btw is nice
